# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8888
    context-path: /api

spring:
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        timeout: 6000
        pool:
            max-active: 1000
            max-wait: -1
            max-idle: 10
            min-idle: 5
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    profiles:
        active: dev